name: bioinformatic

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # ─── Contrôle qualité des lectures ───────────────────────────────────────────
  - fastqc          # Rapport qualité des fichiers FASTQ
  - fastp           # Trimming et filtrage des lectures
  - multiqc         # Agrège les rapports FastQC / fastp
  - porechop        # Trimming nanopore des adaptateurs
  - filtlong        # Filtrage nanopore selon la taille
  - NanoPlot        # Rapport de qualite des Fastq Nanopore

  # ─── Téléchargement de données (NCBI SRA) ────────────────────────────────────
  - sra-tools       # prefetch, fastq-dump, fasterq-dump
  - openssl
  - ca-certificates

  # ─── Estimation / distance entre génomes ────────────────────────────────────
  - mash            # Comparaison rapide de génomes
 # - kraken2            # Comparaison rapide de génomes

  # ─── Assemblage de génome ────────────────────────────────────────────────────
  - spades          # Assembleur Illumina
  - flye            # Assembleur Nanopore

  # ─── Évaluation de l'assemblage ─────────────────────────────────────────────
  - quast           # Qualité d’assemblage
  - busco           # Complétude génomique

  # ─── Typage et caractérisation des bactéries ────────────────────────────────
  - mlst            # Typage MLST
  - ectyper         # Sérotypage E. coli
  - abricate        # Résistances, plasmides, virulence

  # ─── Résistance aux antimicrobiens ──────────────────────────────────────────
  - ncbi-amrfinderplus  # Gènes de résistance AMR
